# Generated by Django 4.2.11 on 2026-04-10 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_sessions', models.PositiveIntegerField(default=0)),
                ('total_messages', models.PositiveIntegerField(default=0)),
                ('kb_hits', models.PositiveIntegerField(default=0)),
                ('llm_hits', models.PositiveIntegerField(default=0)),
                ('fallback_hits', models.PositiveIntegerField(default=0)),
                ('avg_similarity', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'daily_stats',
                'ordering': ['-date'],
            },
        ),
    ]
